component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/org/.*
- ./bin/org/jgrapht/.*
- ./bin/org/jgrapht/alg/.*
- ./bin/org/jgrapht/alg/util/.*
- ./bin/org/jgrapht/demo/.*
- ./bin/org/jgrapht/event/.*
- ./bin/org/jgrapht/experimental/.*
- ./bin/org/jgrapht/experimental/alg/.*
- ./bin/org/jgrapht/experimental/alg/color/.*
- ./bin/org/jgrapht/experimental/dag/.*
- ./bin/org/jgrapht/experimental/equivalence/.*
- ./bin/org/jgrapht/experimental/isomorphism/.*
- ./bin/org/jgrapht/experimental/isomorphism/comparators/.*
- ./bin/org/jgrapht/experimental/permutation/.*
- ./bin/org/jgrapht/experimental/touchgraph/.*
- ./bin/org/jgrapht/ext/.*
- ./bin/org/jgrapht/generate/.*
- ./bin/org/jgrapht/graph/.*
- ./bin/org/jgrapht/traverse/.*
- ./bin/org/jgrapht/util/.*
- ./etc/.*
- ./javadoc/.*
- ./javadoc/org/.*
- ./javadoc/org/jgrapht/.*
- ./javadoc/org/jgrapht/alg/.*
- ./javadoc/org/jgrapht/alg/util/.*
- ./javadoc/org/jgrapht/demo/.*
- ./javadoc/org/jgrapht/event/.*
- ./javadoc/org/jgrapht/ext/.*
- ./javadoc/org/jgrapht/generate/.*
- ./javadoc/org/jgrapht/graph/.*
- ./javadoc/org/jgrapht/traverse/.*
- ./javadoc/org/jgrapht/util/.*
- ./lib/.*
